### ISSUE TITLE
android new sms structure

### ISSUE THREAD

**Issue by lukasa1993** [transitive-bullshit/parse-otp-message#1]
will this be able to parse android sms retriever api ?

**Comment by transitive-bullshit** [comment]
I'm not sure what you're referring to, but this library deals with plaintext **strings**. If you have some higher level representation of an SMS, then it's up to you to convert that to the SMS's string content.

**Comment by lukasa1993** [comment]
i refer to this https://developers.google.com/identity/sms-retriever/verify#generating_a_one-time_code


```
<#> Your ExampleApp code is: 123ABC78
FA+9qCX9VSu
```

to parsw this kind of sms. i manages to parse it with this lib needs removing <#> and trimming after

**Comment by transitive-bullshit** [comment]
Thanks for bringing this up; I just released a new version `v1.0.2` that should support this use case.

Here's the associated [unit test](https://github.com/transitive-bullshit/parse-otp-message/blob/master/test/index.js#L451-L457).

**Comment by transitive-bullshit** [comment]
Please consider starring this repo if you've found the library useful 😄
