### ISSUE TITLE
Requirements for implementation in other languages

### ISSUE THREAD

**Issue by pykenny** [transitive-bullshit/parse-otp-message#13]
Hi,

I found this library useful in my current use case, but the environment I'm working on is not JS/Node.js. In addition to MIT licensing, is there any additional requirements or procedure to follow for implementation in other languages (such as Python)?

**Comment by transitive-bullshit** [comment]
No requirements; feel free to copy / fork / edit 😄 

Linking back to this repo is of course appreciated, but not required.
